server:
  image:
    tag: "v2.45.5"
  remoteWrite:
    - url: http://vmauth-demo.default.svc.cluster.local:8427/insert/0/prometheus  
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - prometheus
          topologyKey: kubernetes.io/hostname
  persistentVolume:
    enabled: false
  replicaCount: 2
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  statefulSet:
    enabled: true
  service:
    type: NodePort
    nodePort: 30090
    statefulsetReplica:
      enabled: true
      replica: 0
  global:
    evaluation_interval: 1m
    scrape_interval: 1m
    scrape_timeout: 10s

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: true
  selfMonitor:
    enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: true

