server:
  image:
    tag: "v2.45.3"
  remoteWrite:
    - url: http://vmauth-demo.default.svc.cluster.local:8427/insert/0/prometheus  
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - prometheus
          topologyKey: kubernetes.io/hostname
  persistentVolume:
    enabled: false
  replicaCount: 2
  service:
    type: NodePort
    nodePort: 30090
  global:
    evaluation_interval: 1m
    scrape_interval: 1m
    scrape_timeout: 10s
serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: 'kubelet'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    - job_name: 'cadvisor'
      kubernetes_sd_configs:
      - role: node
      metrics_path: /metrics/cadvisor
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    - job_name: 'k8apiserver'
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_service_name
          - __meta_kubernetes_endpoint_port_name
        regex: default;kubernetes;https
        action: keep
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        #insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    - job_name: 'k8services'
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_service_name
        regex: default;kubernetes
        action: drop
      - source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_service_label_app_kubernetes_io_instance
          - __meta_kubernetes_service_label_app_kubernetes_io_name
        regex: default;demo;mailpit
        action: drop
      - source_labels:
          - __meta_kubernetes_namespace
        regex: default
        action: keep
      - source_labels:
          - __meta_kubernetes_service_name
        target_label: job
      - source_labels:
          - __address__
        regex: (.+):8400
        action: drop
      - source_labels:
          - __address__
        regex: (.+):8401
        action: drop
      - source_labels:
          - __address__
        regex: (.+):9094
        action: drop
    - job_name: 'k8pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_container_port_name
        regex: metrics
        action: keep
      - source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: job
      scrape_interval: 5m
      scrape_timeout: 30s

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: true

