apiVersion: v1
kind: Pod
metadata:
  name: httpdump
  labels:
    app: httpdump
spec:
  containers:
  - name: httpdump
    image: localhost:5001/httpdump:v0.0.1
    args:
      - "8888"
      - "httpbin.org:80"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 8888
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: httpdump
spec:
  selector:
    app: httpdump
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
