apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-fluent-bit
  namespace: default
  labels:
    app.kubernetes.io/component: logger
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: logger
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/component: logger
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/instance: demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: "/api/v2/metrics/prometheus"
    spec:
      # TODO: for debug
      #      nodeSelector:
      #        kubernetes.io/hostname: kind-worker4
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:3.2.4
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 2020
            initialDelaySeconds: 10
            periodSeconds: 60
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config-volume
              mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config-volume
          configMap:
            name: fluent-bit-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    warn
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_PORT    2020
        Health_Check On
        HC_Errors_Count 5
        HC_Retry_Failure_Count 5
        HC_Period 5

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name         kubernetes
        Match        kube.*
        Kube_URL     https://kubernetes.default.svc:443
        Merge_Log    On
        Keep_Log     Off

    [FILTER]
        Name         grep
        Match        kube.*
        Exclude      $kubernetes['container_name'] kindnet-cni

    [Output]
        Name         http
        Match        *
        host         vlogs-demo-vlogs.default.svc.cluster.local
        port         9428
        uri          /insert/jsonline?_stream_fields=kubernetes.container_name,kubernetes.host,kubernetes.namespace_name,kubernetes.pod_ip,kubernetes.pod_name&_msg_field=log&_time_field=date
        format       json_lines
        json_date_format iso8601

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
