---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/instance: demo
  name: mailpit-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: mailpit
      app.kubernetes.io/instance: demo
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: mailpit
        app.kubernetes.io/instance: demo
    spec:
      containers:
        - name: mailpit-server
          image: "axllent/mailpit:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8025
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8025
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /livez
              port: 8025
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: "true"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/instance: demo
  name: mailpit-demo-nodeport
  namespace: default
spec:
  ports:
    - name: http
      port: 8025
      protocol: TCP
      targetPort: 8025
      nodePort: 30025
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/instance: demo
  type: "NodePort"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/instance: demo
  name: mailpit-demo-smtp
  namespace: default
spec:
  ports:
    - name: smtp
      port: 1025
      protocol: TCP
      targetPort: 1025
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/instance: demo

---
# mailpit-demo-smtp.default.svc.cluster.local
