apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  # You must use the @sha256 digest to guarantee an image built for your kind version.
  # https://github.com/kubernetes-sigs/kind/releases
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  extraPortMappings:
  - containerPort: 30000
    hostPort: 3000
  - containerPort: 30025
    hostPort: 8025
  - containerPort: 30080
    hostPort: 8080
  - containerPort: 30090
    hostPort: 9090
  - containerPort: 30093
    hostPort: 9093
- role: worker
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  extraMounts:
    - hostPath: %STORAGE_PATH%/storage/worker1/1
      containerPath: /pv1
    - hostPath: %STORAGE_PATH%/storage/worker1/2
      containerPath: /pv2
    - hostPath: %STORAGE_PATH%/storage/worker1/3
      containerPath: /pv3
- role: worker
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  extraMounts:
    - hostPath: %STORAGE_PATH%/storage/worker2/1
      containerPath: /pv1
    - hostPath: %STORAGE_PATH%/storage/worker2/2
      containerPath: /pv2
    - hostPath: %STORAGE_PATH%/storage/worker2/3
      containerPath: /pv3
- role: worker
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  extraMounts:
    - hostPath: %STORAGE_PATH%/storage/worker3/1
      containerPath: /pv1
    - hostPath: %STORAGE_PATH%/storage/worker3/2
      containerPath: /pv2
    - hostPath: %STORAGE_PATH%/storage/worker3/3
      containerPath: /pv3
- role: worker
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  extraMounts:
    - hostPath: %STORAGE_PATH%/storage/worker4/1
      containerPath: /pv1
    - hostPath: %STORAGE_PATH%/storage/worker4/2
      containerPath: /pv2
    - hostPath: %STORAGE_PATH%/storage/worker4/3
      containerPath: /pv3

