apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.29.2
  extraPortMappings:
  - containerPort: 30000
    hostPort: 3000
  - containerPort: 30025
    hostPort: 8025
  - containerPort: 30080
    hostPort: 8080
  - containerPort: 30090
    hostPort: 9090
  - containerPort: 30093
    hostPort: 9093
- role: worker
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  extraMounts:
    - hostPath: %STORAGE_PATH%/storage/worker1/1
      containerPath: /pv1
    - hostPath: %STORAGE_PATH%/storage/worker1/2
      containerPath: /pv2
    - hostPath: %STORAGE_PATH%/storage/worker1/3
      containerPath: /pv3
- role: worker
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  extraMounts:
    - hostPath: %STORAGE_PATH%/storage/worker2/1
      containerPath: /pv1
    - hostPath: %STORAGE_PATH%/storage/worker2/2
      containerPath: /pv2
    - hostPath: %STORAGE_PATH%/storage/worker2/3
      containerPath: /pv3
- role: worker
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  extraMounts:
    - hostPath: %STORAGE_PATH%/storage/worker3/1
      containerPath: /pv1
    - hostPath: %STORAGE_PATH%/storage/worker3/2
      containerPath: /pv2
    - hostPath: %STORAGE_PATH%/storage/worker3/3
      containerPath: /pv3

