apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"

nodes:
  - role: control-plane
    # You must use the @sha256 digest to guarantee an image built for your kind version.
    # https://github.com/kubernetes-sigs/kind/releases
    image: kindest/node:v1.33.1@sha256:8d866994839cd096b3590681c55a6fa4a071fdaf33be7b9660e5697d2ed13002
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
      - containerPort: 30025
        hostPort: 8025
      - containerPort: 30080
        hostPort: 8080
      - containerPort: 30090
        hostPort: 9090
      - containerPort: 30093
        hostPort: 9093
      - containerPort: 30427
        hostPort: 8427
      - containerPort: 30428
        hostPort: 9428
      - containerPort: 30091
        hostPort: 9091
