apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"

nodes:
  - role: control-plane
    # You must use the @sha256 digest to guarantee an image built for your kind version.
    # https://github.com/kubernetes-sigs/kind/releases
    image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
      - containerPort: 30025
        hostPort: 8025
      - containerPort: 30080
        hostPort: 8080
      - containerPort: 30090
        hostPort: 9090
      - containerPort: 30093
        hostPort: 9093
      - containerPort: 30427
        hostPort: 8427
      - containerPort: 30428
        hostPort: 9428
