apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: demo-vlogs
  namespace: default
  # 2025-06-07 18:10 It is not recognized even if annotations: is written here.
spec:
  podMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9428"
  logLevel: "WARN"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - "vlsingle"
          topologyKey: "kubernetes.io/hostname"
  futureRetention: "2d"
  image:
    repository: localhost:5001/victoriametrics/victoria-logs
    tag: local
    pullPolicy: IfNotPresent
  logIngestedRows: false
  logNewStreams: false
  replicaCount: 1
  retentionPeriod: "7d"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  storage:
    resources:
      requests:
        storage: 1Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    storageClassName: local-storage4
---
apiVersion: v1
kind: Service
metadata:
  name: vlsingle-demo-nodeport
  namespace: default
spec:
  ports:
    - name: http
      port: 9428
      protocol: TCP
      targetPort: 9428
      nodePort: 30428
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: demo-vlogs
    app.kubernetes.io/name: vlsingle
  sessionAffinity: None
  type: "NodePort"
