apiVersion: v1
kind: ConfigMap
metadata:
  name: my-prometheus-server
  namespace: default
data:
  prometheus.yml: |
    remote_write:
      - url: http://vminsert-example-vmcluster-persistent.monitoring.svc.cluster.local:8480/insert/0/prometheus

