apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: demo
  namespace: default
  labels:
    app.kubernetes.io/name: vmalertmanager
spec:
  image:
    repository: prom/alertmanager
    tag: v0.27.0
    pullPolicy: IfNotPresent
  dnsConfig:
    searches:
      - default.svc.cluster.local
  replicaCount: 3
  configSecret: vmalertmanager-demo-secret
  selectAllByDefault: true

---

apiVersion: v1
kind: Service
metadata:
  name: vmalertmanager-demo-nodeport
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
      nodePort: 30093
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmalertmanager
    app.kubernetes.io/instance: demo
  sessionAffinity: None
  type: "NodePort"

---

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: demo
  namespace: default
  labels:
    app.kubernetes.io/name: vmalert
spec:
  image:
    repository: victoriametrics/vmalert
    tag: v1.93.13
    pullPolicy: IfNotPresent
  replicaCount: 2
  evaluationInterval: "10s"
  selectAllByDefault: true
  datasource:
    url: http://vmauth-demo.default.svc.cluster.local:8427/select/0/prometheus
  notifiers:
    - url: http://vmalertmanager-demo-0.vmalertmanager-demo:9093
    - url: http://vmalertmanager-demo-1.vmalertmanager-demo:9093
    - url: http://vmalertmanager-demo-2.vmalertmanager-demo:9093
  remoteWrite:
    url: http://vminsert-demo-vmcluster-persistent.default.svc.cluster.local:8480/insert/0/prometheus
  remoteRead:
    url: http://vmauth-demo.default.svc.cluster.local:8427/select/0/prometheus

---

apiVersion: v1
kind: Service
metadata:
  name: vmalert-demo-nodeport
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmalert
    app.kubernetes.io/instance: demo
  sessionAffinity: None
  type: "NodePort"

