apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: demo
  namespace: default
  labels:
    app.kubernetes.io/name: vmauth
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicaCount: 3
  selectAllByDefault: true
  image:
    repository: victoriametrics/vmauth
    tag: v1.108.1
    pullPolicy: IfNotPresent
  extraArgs:
    #loggerFormat: "json"
    loggerLevel: "WARN"
    discoverBackendIPs: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - "vmauth"
          topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      cpu: "125m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  unauthorizedAccessConfig:
    - src_paths:
        - "/insert/.+"
      url_prefix:
        - http://vminsert-demo-vmcluster-persistent:8480
    - src_paths:
        - "/select/.+"
      url_prefix:
        - http://vmselect-demo-vmcluster-persistent:8481

---
apiVersion: v1
kind: Service
metadata:
  name: vmauth-demo-nodeport
  namespace: default
spec:
  ports:
    - name: http
      port: 8427
      protocol: TCP
      targetPort: 8427
      nodePort: 30427
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: vmauth
    app.kubernetes.io/instance: demo
  sessionAffinity: None
  type: "NodePort"
