apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: demo
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicaCount: 3
  selectAllByDefault: true
  image:
    repository: victoriametrics/vmauth
    tag: v1.101.0
    pullPolicy: IfNotPresent
  extraArgs:
    discoverBackendIPs: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - "vmauth"
          topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      cpu: "125m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  unauthorizedAccessConfig:
    - src_paths:
        - "/insert/.+"
      url_prefix:
        - http://vminsert-demo-vmcluster-persistent.default.svc.cluster.local:8480
    - src_paths:
        - "/select/.+"
      url_prefix:
        - http://vmselect-demo-vmcluster-persistent.default.svc.cluster.local:8481

