---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: demo-vmcluster-persistent
  namespace: default
spec:
  retentionPeriod: 7d
  replicationFactor: 2
  vmstorage:
    replicaCount: 3
    storageDataPath: "/vm-data"
    image:
      repository: victoriametrics/vmstorage
      tag: v1.101.0-cluster
      pullPolicy: IfNotPresent
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vmstorage"
          topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        metadata:
          name: vmstorage-pvc
        spec:
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
          accessModes:
            - ReadWriteOnce
          storageClassName: local-storage
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
  vmselect:
    replicaCount: 2
    image:
      repository: victoriametrics/vmselect
      tag: v1.101.0-cluster
      pullPolicy: IfNotPresent
    cacheMountPath: "/select-cache"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vmselect"
          topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 200Mi
    resources:
      limits:
        cpu: 250m
        memory: "500Mi"
  vminsert:
    replicaCount: 2
    image:
      repository: victoriametrics/vminsert
      tag: v1.101.0-cluster
      pullPolicy: IfNotPresent
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vminsert"
          topologyKey: "kubernetes.io/hostname"
    resources:
      limits:
        cpu: 250m
        memory: "500Mi"
