apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: demo-downsampling
  namespace: default
  labels:
    app.kubernetes.io/name: vmagent
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicaCount: 2
  image:
    repository: victoriametrics/vmagent
    tag: v1.105.0
    pullPolicy: IfNotPresent
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - "vmagent"
          topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      cpu: "250m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      metadata:
        name: vmagent-statefulstorage-pvc
      spec:
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage3
  remoteWrite:
    - url: http://vmauth-demo:8427/insert/1/prometheus
  extraArgs:
    promscrape.maxScrapeSize: 64MB
  scrapeInterval: 10m
  selectAllByDefault: false
  inlineScrapeConfig: |
    - job_name: "downsampling"
      stream_parse: true
      static_configs:
        - targets:
          - vmauth-demo:8427/select/0/prometheus/federate
      honor_labels: true
      metrics_path: /federate
      params:
        'match[]': ['{__name__!=""}']
