apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: vmalertmanagerconfig-demo
  namespace: default
spec:
  route:
    receiver: email
  receivers:
    - name: email
      email_configs:
        - send_resolved: false
          to: 'alert@example.com'
          from: 'alertmanager@example.com'
          hello: 'mail.example.com'
          smarthost: 'mailpit-demo-smtp.default.svc.cluster.local:1025'
          require_tls: false

