adminUser: admin
adminPassword: adminadmin

testFramework:
  enabled: false

service:
  type: NodePort
  nodePort: 30000
  annotations:
    prometheus.io/probe: "true"

plugins:
  - https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.13.3/victoriametrics-metrics-datasource-v0.13.3.zip;victoriametrics-metrics-datasource

grafana.ini:
  plugins:
    allow_loading_unsigned_plugins: victoriametrics-metrics-datasource
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
    level: warn
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ tpl (.Values.ingress.hosts | first) . }}{{ else }}''{{ end }}"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: "Prometheus"
        type: prometheus
        access: proxy
        url: http://vmauth-demo:8427/select/0/prometheus
        isDefault: true
      - name: "Prometheus Downsampled"
        type: prometheus
        access: proxy
        url: http://vmauth-demo:8427/select/1/prometheus
        isDefault: false
      - name: "VictoriaMetrics"
        type: victoriametrics-metrics-datasource
        access: proxy
        url: http://vmauth-demo:8427/select/0/prometheus
        isDefault: false
      - name: "VictoriaMetrics Downsampled"
        type: victoriametrics-metrics-datasource
        access: proxy
        url: http://vmauth-demo:8427/select/1/prometheus
        isDefault: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/1860/revisions/37/download
    alertmanager:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/9578/revisions/4/download
    victoriametrics-cluster:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/11176/revisions/39/download
    victoriametrics-vmalert:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/14950/revisions/13/download
    victoriametrics-operator:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/17869/revisions/3/download
    victoriametrics-vmauth:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/21394/revisions/2/download
    prometheus-2-0:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/3662/revisions/2/download
    blackbox-exporter_HTTP:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/13659/revisions/1/download
    victoriametrics-vmagent:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/12683/revisions/21/download
    victorialogs:
      datasource: Prometheus
      url: https://grafana.com/api/dashboards/22084/revisions/3/download
    fluent-bit:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/fluent/fluent-bit-docs/refs/heads/master/monitoring/dashboard.json
